name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: azure/static-web-apps-deploy@v1  # <--- Asigură-te că aceasta este indentată corect!
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NEBSHOME_APP_XXXXX }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://docs.microsoft.com/azure/static-web-apps/github-actions-workflow
          app_location: "/" # <--- AICI! Asigură-te că este "/"
          api_location: "" # e.g. "api"
          output_location: "" # <--- AICI! Asigură-te că este "" (gol)
          ###### End of Repository/Build Configurations ######
